DjangoLibraryApp/DjangoLibraryApp/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DjangoLibraryApp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('Library.urls', namespace="Library")), 
)

DjangoLibraryApp/Library/urls.py
from django.conf.urls import patterns, url

from Library import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'Library/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'Library/index.html'}, name='logout'),
    url(r'^signup/$', views.register_account, name='signup'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^book/all/', views.SystemBookView.as_view(), name='detail_system'),
    url(r'^library/(?P<pk>\d+)/$', views.LibraryBookView.as_view(), name='detail_library'),
    url(r'^book/(?P<pk>\d+)/$', views.BookView.as_view(), name='detail_book'),
    url(r'^book/(?P<book_id>\d+)/checkout/$', views.checkout_or_return, name='checkout_or_return')
)

DjangoLibraryApp/Library/models.py
from django.db import models
from django.contrib.auth.models import User
# Used to handle model edge-cases
from django.core.exceptions import ValidationError

# For use in time related calculations
from django.utils import timezone
import datetime

class Library(models.Model):

    def __unicode__(self):
        return self.name
    
    name = models.CharField(max_length=100)
    max_shelves = models.IntegerField(default=0)
    max_books = models.IntegerField(default=0)
    
    def shelves(self):
        return self.shelf_set.count()

    def books(self):
        num_books = 0
        for shelf in self.shelf_set.all():
            num_books += shelf.book_set.count()
        return num_books

class Shelf(models.Model):
    
    def __unicode__(self):
        return self.library.name + "_" + self.shelf_code

    library = models.ForeignKey(Library)
    shelf_code = models.CharField(max_length=5)
    max_books = models.IntegerField(default=0)

    def books(self):
        return self.book_set.count()
  
    def clean(self):
        if self.library.shelves() == self.library.max_shelves:
            raise ValidationError("Failed to add shelf to library; library is at shelf capacity!")
        if self.library.books() + self.books() > self.library.max_books:
            raise ValidationError("Failed to add shelf to library; library is at book capacity!")
    
class Book(models.Model):
    
    def __unicode__(self):
        return self.title
    
    shelf = models.ForeignKey(Shelf, null=True, blank=True)
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    genre = models.CharField(max_length=50, blank=True)
    language = models.CharField(max_length=25, blank=True)
    publisher = models.CharField(max_length=100)
    pub_date = models.DateField('Date published')
    isbn = models.CharField(max_length=13)
    condition = models.CharField(max_length=10, blank=True)
    checkout_status = models.BooleanField(default=False)
    checkout_client = models.ForeignKey(User, null=True, blank=True)

    def availability(self):
        if self.checkout_status == True:
            return "Checked Out"
        else:
            return "Available"
    availability.admin_order_field = "checkout_status"

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=30) <= self.pub_date < now 
    was_published_recently.admin_order_field = "pub_date"
    was_published_recently.short_description = "Published Recently?"
    was_published_recently.boolean = True

    def clean(self): 
        if self.shelf and self.shelf.books() == self.shelf.max_books:
            raise ValidationError("Failed to add book to shelf; shelf is full!")

DjangoLibraryApp/Library/views.py
from django.core.exceptions import *
from django.contrib.auth.models import User
from django.shortcuts import render 
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.views import generic

from Library.models import * 
# Create your views here.
class IndexView(generic.ListView):
    model = Library 
    template_name = 'Library/index.html'
    context_object_name = 'home_data'

    def get_context_data(self, **kwargs):
        time = timezone.now()
        context = super(IndexView, self).get_context_data(**kwargs)
        context['library_list'] = Library.objects.all()
        context['recently_checked_out_books'] = Book.objects.filter(checkout_status=True)
        context['recently_checked_in_books'] = Book.objects.filter(checkout_status=False)
        context['recent_books'] = Book.objects.filter(pub_date__lte=time).order_by('pub_date').reverse()[:5]
        return context

class AboutView(generic.TemplateView):
    template_name = 'Library/about.html'

class SearchView(generic.ListView):
    template_name = 'Library/system_books.html'
    context_object_name = 'book_list'
    
    def post(self, request):
        search = request.POST.get('searchBook', None)
        search_type = request.POST.get('choice', None)

        if (search_type == 'title'):
            book_list = Book.objects.filter(title__icontains=search)
            print book_list
        elif (search_type == 'author'):
            book_list = Book.objects.filter(author__icontains=search)
        elif (search_type == 'publisher'):
            book_list = Book.objects.filter(publisher__icontains=search)
        elif (search_type == 'isbn'):
            book_list = Book.objects.filter(isbn__icontains=search)
        elif (search_type == None):
            book_list = Book.objects.filter(title__icontains=search) 
        
        return render(request, 'Library/system_books.html', {'book_list': book_list})

class SystemBookView(generic.ListView):
    template_name = 'Library/system_books.html'
    context_object_name = 'book_list'
    
    def get_queryset(self):
        return Book.objects.filter(pub_date__lte=timezone.now()).order_by('title')

class LibraryBookView(generic.DetailView):
    model = Library 
    template_name = 'Library/library_books.html' 

class BookView(generic.DetailView):
    model = Book
    template_name = 'Library/book.html'

def register_account(request):
    try:
        user = request.POST['username']
        passwd = request.POST['password']
        email = request.POST['email']
        firstName = request.POST['firstName']
        lastName = request.POST['lastName']
        try:
            user = User.objects.get(username=user)
        except User.DoesNotExist:
            user = User.objects.create_user(username=user, password=passwd)
            user.email = email
            user.first_name = firstName
            user.last_name = lastName
            user.save()
            return HttpResponseRedirect('/')
        else:
            return HttpResponse("Username already in use")
    except:
        return HttpResponse("Something else unexpected happened.")

def checkout_or_return(request, book_id):
    try:
        user = User.objects.get(username=request.user)
        book = Book.objects.get(id=book_id)
        if (book.checkout_client is not None and book.checkout_client==user):
            book.checkout_client = None
            book.checkout_status = False
        else:
            if (user.book_set.count() < 8):
                book.checkout_client = user 
                book.checkout_status = True
        book.save()
        return HttpResponseRedirect('/') 
    except:
        return HttpResponse("Something else unexpected happened.")

DjangoLibraryApp/Library/templates/Library/about.html
<html>
	<head>
        <!-- Authors: Giuseppe Scoppino, Nathanael Thompson 2013-2014 -->
        {% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'Library/css/styles.css' %}" />
		<h1>Library System</h1>
		<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
		<title>
			Library System
		</title>
	</head>
	<br>
	<body>
        <div id = "container">
            <a HREF = "http://spsu.edu"><IMG id = "logo" SRC="{% static 'Library/images/spsu.gif' %}"></a>
            <div id="header"> 
                <a class="menu" href="{% url 'Library:index' %}">Home</a> | 
                <a class="menu" href="{% url 'Library:about' %}">About</a> | 
                {% if user.is_authenticated %}
                <a class="menu" href="{% url 'Library:logout' %}" title="Logout when ready.">Logout</a> |
                {% else %}
                <a class="menu" href="{% url 'Library:login' %}" title="Login to check in/out books.">Login</a> |
                {% endif %}
                <a class="menu" href="{% url 'Library:detail_system' %}">Books</a>
            </div>
            <br><br><br>
            <h2><b>About the Library System</b></h2>
            <p>
               The Library Web System meets the needs of library administrators and clients alike, providing 
               the ability to manipulate a database of books, shelves, libraries, and users representing 
               the corresponding real work information.
            </p>
        </div>
	</body>
</html>

DjangoLibraryApp/Library/templates/Library/book.html
<html>
	<head>
        <!-- Authors: Giuseppe Scoppino, Nathanael Thompson 2013-2014 -->
        {% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'Library/css/styles.css' %}" />
		<h1>Library System</h1>
		<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
		<title>
			Library System
		</title>
	</head>
	<br>
	<body>
        <div id = "container">
            <a HREF = "http://spsu.edu"><IMG id = "logo" SRC="{% static 'Library/images/spsu.gif' %}"></a>
            <div id="header"> 
                <a class="menu" href="{% url 'Library:index' %}">Home</a> | 
                <a class="menu" href="{% url 'Library:about' %}">About</a> | 
                {% if user.is_authenticated %}
                <a class="menu" href="{% url 'Library:logout' %}" title="Logout when ready.">Logout</a> |
                {% else %}
                <a class="menu" href="{% url 'Library:login' %}" title="Login to check in/out books.">Login</a> |
                {% endif %}
                <a class="menu" href="{% url 'Library:detail_system' %}">Books</a>
            </div>
            <br><br><br>
            <h2><b>{{book.title}}</b></h2>
            <p>
                <p><b>Author: </b>{{book.author}}</p>
                <p><b>Publisher: </b>{{book.publisher}}</p>
                <p><b>Publish Date: </b>{{book.pub_date}}</p>
                <p><b>ISBN: </b>{{book.isbn}}</p>
                <p><b>Condition: </b>{{book.condition}}</p>
                <p><b>Checkout Status: </b>{{book.checkout_status}}</p>
            </p>
            {% if user.is_authenticated %}
                <form method="post" action="{% url 'Library:checkout_or_return' book.id %}">
                    {% csrf_token %} 
                    {% if book.checkout_status == True %}
                    <input type="submit" value="Return Book"/>
                    {% else %}
                    <input type="submit" value="Checkout Book"/>
                    {% endif %}
                </form>
            {% endif %}
        </div>
	</body>
</html>

DjangoLibraryApp/Library/templates/Library/index.html
<html>
	<head>
        <!-- Authors: Giuseppe Scoppino, Nathanael Thompson 2013-2014 -->
        {% load staticfiles %}
		<h1 class="title">Library System</h1>
		<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
		<title>Library System</title>
		<link rel="stylesheet" type="text/css" href="{% static 'Library/css/styles.css' %}" />
	</head>

	<body>
		<div id = "news">
            <h2><b><u>New Releases</u></b></h2>
                {% for book in recent_books.all %}
                    <p>
                    <a href="{% url 'Library:detail_book' book.id %}">{{book.title}} ({{book.pub_date.year}})</a>
                    {% if book.checkout_status == True %}
                    <label>(Checked Out)</label>
                    {% endif %}
                    </p>
                {% endfor %}
		</div>
		<div id = "books">
			<h2><b><u>Checkout Information</u></b></h2>
            {% if user.is_authenticated %}
                <h4>Recently Checked Out Books</h4>
                {% for book in user.book_set.all %} 
                    <p><a href="{% url 'Library:detail_book' book.id %}">{{book.title}}</a></p>
                {% endfor %}
            {% endif %}
			
			<h4>Recently Returned Books</h4>
                {% for book in recently_checked_in_books %}
                    <!--<a href="{% url 'Library:detail_book' book.id %}">{{book.title}}</li> -->
                {% endfor %}
		</div>
		<div id="container">
            <div id = "clock" style="text-align:center;">
            </div>
            <div id="header"> 
                <a class="menu" href="{% url 'Library:index' %}">Home</a> | 
                <a class="menu" href="{% url 'Library:detail_system' %}" title="Browse all books.">Books</a> | 
                {% if user.is_authenticated %}
                <a class="menu" href="{% url 'Library:logout' %}" title="Logout when ready.">Logout</a> |
                {% else %}
                <a class="menu" href="{% url 'Library:login' %}" title="Login to check in/out books.">Login</a> |
                {% endif %}
                <a class="menu" href="{% url 'Library:about' %}">About</a> 
            </div>
            <a href="http://spsu.edu"><IMG id ="logo" SRC="{% static 'Library/images/spsu.gif' %}"></a>
            <div id="description">	
                {% if user.is_authenticated %}
                    <p><em>Welcome back, {{user.username}}.</em></p>
                {% else %}
                    <p><em>Welcome, guest. </em></p>
                    <p>Have an existing account? <a href="{% url 'Library:login' %}">Login</a> to begin checking out books.</p>
                    <p>New to Library System? <a href="{% url 'Library:login' %}">Create an account</a> to get started!</p>
                {% endif %} 
            </div>
            <br>
            <p>You can choose a library from the drop-down menu to browse its available books.</p> 
            <select id="library_selector"> 
                <option></option>
                {% for library in library_list.all %}
                    <option value="/library/{{ library.id }}">{{ library.name }}</option>
                {% endfor %}
            </select>
            <button id="submit_library" type="submit">Go</button>
            <p>Or, search for a book directly in the input field below:</p>
            <form method="post" action="{% url 'Library:search' %}">
                {% csrf_token %}
                <input type="text" name="searchBook" /><br>
                <input type="radio" name="choice" value="title">Title</input>
                <input type="radio" name="choice" value="author">Author</input>
                <input type="radio" name="choice" value="publisher">Publisher</input>
                <input type="radio" name="choice" value="isbn">ISBN No.</input>
            <br><br><input type="submit" value="Search" />
            </form>
            <br><br> 
            <hr> 
            <div id="random">
                <h2>News</h2>
                <h3>04/2014: Launch!</h3>
                <p>The web portal to the Library system is now active. With it, you can
                   look through books located in libraries in our system, and, if you have a 
                   library account, request a checkout.</p>
            </div>
        </div>
	
        <script type="text/javascript" src="{% static 'Library/js/index.js' %}"></script>
	</body>
</html>

DjangoLibraryApp/Library/templates/Library/library_books.html
<html>
	<head>
        <!-- Authors: Giuseppe Scoppino, Nathanael Thompson 2013-2014 -->
        {% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'Library/css/styles.css' %}" />
		<h1 class ="title">Library System</h1>
		<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
			<title>
				Library System
			</title>
	</head>
	
	<body>
		<div id ="container">
			<a HREF = "http://spsu.edu"><IMG id = "logo" SRC="{% static 'Library/images/spsu.gif' %}"></a>
			<div id = "header"> 
				<a class="menu" href="{% url 'Library:index' %}">Home</a> | 
				{% if user.is_authenticated %}
                <a class="menu" href="{% url 'Library:logout' %}" title="Logout when ready.">Logout</a> |
                {% else %}
                <a class="menu" href="{% url 'Library:login' %}" title="Login to check in/out books.">Login</a> |
                {% endif %}
				<a class="menu" href="{% url 'Library:about' %}">About</a> |
				<a class="menu" href="{% url 'Library:detail_system' %}">Books</a>
			<br>
			</div>
		    <br>
			<form class="form" method="post" action="">
                {% for shelf in library.shelf_set.all %}
                    <div id="shelf{{shelf.id}}">
                        <h2>{{shelf.library.name}}: Shelf {{shelf.shelf_code}}</h2>
                        <ul>
                            {% for book in shelf.book_set.all %}
                                <li class="book">
                                <input type="checkbox" name="book{{book.id}}" value="{{book.id}}"/>
                                <a id="book{{book.id}}" href="/book/{{book.id}}">{{book.title}}</a>
                                {% if book.checkout_status == True %}
                                <label>(Checked Out)</label>
                                {% endif %}
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
				<input type="submit" value="Submit"/>
			</form>
		</div>
	</body>
</html>

DjangoLibraryApp/Library/templates/Library/login.html
<html>
	<head>
        <!-- Authors: Giuseppe Scoppino, Nathanael Thompson 2013-2014 -->
        {% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'Library/css/styles.css' %}" />
		<h1>Library System</h1>
		

		<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
		<title>
			Library System
		</title>
	</head>
	<body>
	<script type = "text/javascript">
		function validator()
		{
			var firstName = document.forms["surveyForm"]["fnameTB"].value;
			var lastName = document.forms["surveyForm"]["lnameTB"].value;
			var major = document.forms["surveyForm"]["majorTB"].value;
			var email = document.forms["surveyForm"]["emailTB"].value;
			var education = document.forms["surveyForm"]["educationDropdown"].value;
			var male = document.forms["surveyForm"]["maleR"].checked;
			var female = document.forms["surveyForm"]["femaleR"].checked;
			
			var atpos = email.indexOf("@");
			var dotpos = email.lastIndexOf(".");
			
			if(firstName == "" || firstName == null)
			{
				alert("Must fill out all information");
				return false;
			}
			if(lastName == "" || lastName == null)
			{
				alert("Must fill out all information");
				return false;
				
			}
			if(major == "" || major == null)
			{
				alert("Must fill out all information");
				return false;
			}
			
			if (atpos < 1 || dotpos < atpos + 2 || dotpos + 2 >= email.length)
			{
				alert("Not a valid e-mail address");
				return false;
			}
			
			if(male == false && female == false)
			{
				alert("Must fill out all information");
				return false;
			}
			
			document.write('<table border="1" cellspacing="1" cellpadding="5">');
			
			document.write('<tr>');
			document.write('<td>First Name ' + '</td>');
			document.write('<td>' + firstName + '</td>');
			document.write('</tr>');
			
			document.write('<tr>');
			document.write('<td>Last Name ' + '</td>');
			document.write('<td>' + lastName + '</td>');
			document.write('</tr>');
			
			document.write('<tr>');
			document.write('<td>Major ' + '</td>');
			document.write('<td>' + major + '</td>');
			document.write('</tr>');
			
			document.write('<tr>');
			document.write('<td>Email ' + '</td>');
			document.write('<td>' + email + '</td>');
			document.write('</tr>');
			
			document.write('<tr>');
			document.write('<td>Education ' + '</td>');
			document.write('<td>' + education + '</td>');
			document.write('</tr>');
			
			
			document.write('</table>');
			alert("Information conformation");
		}
		
	</script>
	<div id = "container">
        <a HREF = "http://spsu.edu"><IMG style="float:left; margin:20px;" id = "logo" SRC="{% static 'Library/images/spsu.gif' %}"></a>
		<div id = "header"> 
			<a class="menu" href="{% url 'Library:index' %}">Home</a> | 
			 {% if user.is_authenticated %}
            <a class="menu" href="{% url 'Library:logout' %}" title="Logout when ready.">Logout</a> |
            {% else %}
            <a class="menu" href="{% url 'Library:login' %}" title="Login to check in/out books.">Login</a> |
            {% endif %} 
			<a class="menu" href="{% url 'Library:about' %}">About</a> |
			<a class="menu" href="{% url 'Library:detail_system' %}">Books</a>
		<br>
		</div>

        <form name = "loginForm" method="post" action="{% url 'Library:login' %}" style="float:left">
            {% if form.errors %}
                <p><b>Your username and password didn't match. Please try again.</b></p>
            {% else %}
                <p><b>Log in here.</b></p>
            {% endif %}
            {% csrf_token %}
            User name: {{form.username}}<br>
            Password: {{form.password}}<br>
            <input type="submit" value="Login"/> 
            <input type="hidden" name="next" value="{{ next }}"/>
        </form>
		<form name="signupForm" method="post" action="{% url 'Library:signup' %}" style="float:right">
			{% csrf_token %}
            <p><b>Don't have an account? Sign up today!</b></p>
            User Name: <input type="text" name="username"/><br>
            Password <input type="password" name="password"/><br>
			Email: <input type="text" name = "email"/><br>
			First name: <input type="text" name ="firstName"/><br>
			Last name: <input type="text" name = "lastName"/><br>
			<input type="submit" value="Sign Up"/>
			<input type="hidden" name="next" value="/"/>
		</form>
	</div>
	</body>
</html>

DjangoLibraryApp/Library/templates/Library/system_books.html
<html>
	<head>
        <!-- Authors: Giuseppe Scoppino, Nathanael Thompson 2013-2014 -->
        {% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'Library/css/styles.css' %}" />
		<h1 class ="title">Library System</h1>
		<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
			<title>
				Library System
			</title>
	</head>
	
	<body>
		<div id="system_book_container">
			<a HREF = "http://spsu.edu"><IMG id = "logo" SRC="{% static 'Library/images/spsu.gif' %}"></a> 
            <div id = "header"> 
				<a class="menu" href="{% url 'Library:index' %}">Home</a> | 
				<a class="menu" href="{% url 'Library:about' %}">About</a> | 
				{% if user.is_authenticated %}
                <a class="menu" href="{% url 'Library:logout' %}" title="Logout when ready.">Logout</a> |
                {% else %}
                <a class="menu" href="{% url 'Library:login' %}" title="Login to check in/out books.">Login</a> |
                {% endif %}
				<a class="menu" href="{% url 'Library:detail_system' %}">Books</a>
			<br>
			<p>Quick Links: 
			<select onchange = "window.open(this.value, '_self', '');">
				<option> </option>
				<option value = "index.html">Home</option>
				<option value = "faculty.html">Faculty</option>
				<option value = "student_grade.html">Book Selector</option>
				<option value = "survey.html">About</option>
			</select></p>
			</div>
			<form>
				<br>
                <ul>
                {% for aBook in book_list.all %}
                    <li class="book">
                    <input type="checkbox" value="{{aBook.id}}"/>
                    <a id="book{{aBook.id}}" href="{% url 'Library:detail_book' aBook.id %}">{{aBook.title}}</a>
                    {% if aBook.checkout_status == True %}
                        <label>(Checked Out)</label>
                    {% endif %}
                    </li>
                {% if forloop.last %}
                    <input type="submit" value="Submit"/>
                {% endif %}
                {% empty %}
                    <p><b>Sorry, no results are available.</b></p>
                {% endfor %}
                </ul>
			</form>
		</div>
	</body>
</html>